name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # You can specify another version if needed

      - name: Run Flutter Clean
        run: flutter clean

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build APK (Release Mode)
        run: flutter build apk --release

#      - name: Upload APK Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/app-release.apk
